apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-java
spec:
  template:
    spec:
      containers:
        - image: quay.io/klenkes74/knative-helloworld:1.0.1
          env:
            - name: TARGET
              value: "Quarkus Sample v1"
  traffic:
    - tag: v1
      revisionName: helloworld-java-r9s2m
      percent: 100
